source 'https://rubygems.org'
ruby '2.2.3'
#ruby-gemset=cityrecorder

gem 'activesupport', require: 'active_support/all'
gem 'aws-sdk', '~> 2'
gem 'elasticsearch-dsl'
gem 'elasticsearch-persistence'
gem 'es-reindex'
gem 'pry'
gem 'rake'
